services:
  - type: web
    name: trueme-api
    env: node
    plan: starter
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm --filter @trueme/api start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        fromDatabase:
          name: trueme-db
          property: connectionString
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false

databases:
  - name: trueme-db
    databaseName: trueme
    user: trueme
